# docker-compose.yml 
version: '3.8'
services:
  tovarscout:
    build: .
    container_name: tovarscout
    environment:
      - TELEGRAM_TOKEN=your-telegram-token-here
    volumes:
      - ./data:/app/data
    restart: unless-stopped
